name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
- type: checkboxes
  attributes:
    label: Has this feature been requested already?
    description: 
    options:
    - label: I have searched the existing issues and this is a new request.
      required: true
- type: textarea
  attributes:
    label: What is your desired feature/change?
    description: A clear and concise description of what you want changed or added.
  validations:
    required: true
- type: textarea
  attributes:
    label: Why should this be added?
    description: Any reasoning you have for this addition.
    placeholder: e.x "this will improve user experience"
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional notes
    description: Add any other context or screenshots about the feature request here. If you have suggestions on implementation, please place them here.
  validations:
    required: false
